# Generated by Django 3.1.1 on 2023-07-07 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('attend_days', models.IntegerField(default=0, verbose_name='出勤')),
                ('leave_days', models.IntegerField(default=0, verbose_name='请假')),
                ('absent_days', models.IntegerField(default=0, verbose_name='旷班')),
                ('business_days', models.IntegerField(default=0, verbose_name='出差')),
                ('zaotui_days', models.IntegerField(default=0, verbose_name='早退')),
                ('late_days', models.IntegerField(default=0, verbose_name='迟到')),
                ('overtime', models.IntegerField(default=0, verbose_name='加班时长')),
                ('base_salary', models.IntegerField(default=0, verbose_name='基础工资')),
                ('overtime_salary', models.IntegerField(default=0, verbose_name='加班工资')),
                ('kouchu', models.IntegerField(default=0, verbose_name='应扣')),
                ('allowance', models.IntegerField(default=0, verbose_name='补贴')),
                ('should_pay', models.IntegerField(default=0, verbose_name='应发')),
                ('tax', models.IntegerField(default=0, verbose_name='个人所得税')),
                ('actual_pay', models.IntegerField(default=0, verbose_name='实发')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
            options={
                'ordering': ['-current_time'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('staff_age', models.PositiveIntegerField(verbose_name='年龄')),
                ('staff_home', models.CharField(max_length=100, verbose_name='籍贯')),
                ('staff_nationality', models.CharField(max_length=20, verbose_name='民族')),
                ('staff_tel', models.BigIntegerField(verbose_name='电话')),
                ('start_time', models.DateField(auto_now_add=True, verbose_name='入职时间')),
                ('id_card', models.CharField(max_length=20, verbose_name='身份证')),
                ('staff_type', models.CharField(max_length=100, null=True, verbose_name='职位')),
                ('salary_pre_hour', models.IntegerField(verbose_name='时薪')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('flag_leave', models.BooleanField(default=False, verbose_name='请假')),
                ('flag_business', models.BooleanField(default=False, verbose_name='出差')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='上班时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='下班时间')),
                ('supplement', models.CharField(blank=True, default='无', max_length=100, null=True, verbose_name='补充')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
            options={
                'ordering': ['-current_time'],
            },
        ),
    ]
